import type { Endpoints } from '@octokit/types';

type issueType = Endpoints['GET /repos/{owner}/{repo}/issues']['response']['data'][0];
export const issue = {
  id: 1,
  node_id: 'MDU6SXNzdWUx',
  url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347',
  repository_url: 'https://api.github.com/repos/octocat/Hello-World',
  labels_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/labels{/name}',
  comments_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/comments',
  events_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/events',
  html_url: 'https://github.com/octocat/Hello-World/issues/1347',
  number: 1347,
  state: 'open',
  title: 'Found a bug',
  body: "I'm having a problem with this.",
  user: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  labels: [
    {
      id: 208045946,
      node_id: 'MDU6TGFiZWwyMDgwNDU5NDY=',
      url: 'https://api.github.com/repos/octocat/Hello-World/labels/bug',
      name: 'bug',
      description: "Something isn't working",
      color: 'f29513',
      default: true,
    },
  ],
  assignee: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  assignees: [
    {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
  ],
  milestone: {
    url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1',
    html_url: 'https://github.com/octocat/Hello-World/milestones/v1.0',
    labels_url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1/labels',
    id: 1002604,
    node_id: 'MDk6TWlsZXN0b25lMTAwMjYwNA==',
    number: 1,
    state: 'open',
    title: 'v1.0',
    description: 'Tracking milestone for version 1.0',
    creator: {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
    open_issues: 4,
    closed_issues: 8,
    created_at: '2011-04-10T20:09:31Z',
    updated_at: '2014-03-03T18:58:10Z',
    closed_at: '2013-02-12T13:22:01Z',
    due_on: '2012-10-09T23:39:01Z',
  },
  locked: true,
  active_lock_reason: 'too heated',
  comments: 0,
  pull_request: {
    url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347',
    html_url: 'https://github.com/octocat/Hello-World/pull/1347',
    diff_url: 'https://github.com/octocat/Hello-World/pull/1347.diff',
    patch_url: 'https://github.com/octocat/Hello-World/pull/1347.patch',
  },
  closed_at: null,
  created_at: '2011-04-22T13:33:48Z',
  updated_at: '2011-04-22T13:33:48Z',
  closed_by: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  author_association: 'COLLABORATOR',
  state_reason: 'completed',
} satisfies issueType;
export const issueWithoutLabels = {
  id: 1,
  node_id: 'MDU6SXNzdWUx',
  url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347',
  repository_url: 'https://api.github.com/repos/octocat/Hello-World',
  labels_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/labels{/name}',
  comments_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/comments',
  events_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/events',
  html_url: 'https://github.com/octocat/Hello-World/issues/1347',
  number: 1347,
  state: 'open',
  title: 'Found a bug',
  body: "I'm having a problem with this.",
  user: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  assignee: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  assignees: [
    {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
  ],
  milestone: {
    url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1',
    html_url: 'https://github.com/octocat/Hello-World/milestones/v1.0',
    labels_url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1/labels',
    id: 1002604,
    node_id: 'MDk6TWlsZXN0b25lMTAwMjYwNA==',
    number: 1,
    state: 'open',
    title: 'v1.0',
    description: 'Tracking milestone for version 1.0',
    creator: {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
    open_issues: 4,
    closed_issues: 8,
    created_at: '2011-04-10T20:09:31Z',
    updated_at: '2014-03-03T18:58:10Z',
    closed_at: '2013-02-12T13:22:01Z',
    due_on: '2012-10-09T23:39:01Z',
  },
  locked: true,
  active_lock_reason: 'too heated',
  comments: 0,
  pull_request: {
    url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347',
    html_url: 'https://github.com/octocat/Hello-World/pull/1347',
    diff_url: 'https://github.com/octocat/Hello-World/pull/1347.diff',
    patch_url: 'https://github.com/octocat/Hello-World/pull/1347.patch',
  },
  closed_at: null,
  created_at: '2011-04-22T13:33:48Z',
  updated_at: '2011-04-22T13:33:48Z',
  closed_by: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  author_association: 'COLLABORATOR',
  state_reason: 'completed',
} satisfies Omit<issueType, 'labels'>;

export const actionInputs = {
  GITHUB_REPOSITORY: 'aws-actions/stale-issue-cleanup',
  LOGLEVEL: 'DEBUG',
  REPO_TOKEN: 'FAKE-REPO-TOKEN',
  ANCIENT_ISSUE_MESSAGE: 'Ancient issue message.',
  ANCIENT_PR_MESSAGE: 'Ancient Pr message.',
  STALE_ISSUE_MESSAGE: 'Stale issue message.',
  STALE_PR_MESSAGE: 'Stale pr message.',
  DAYS_BEFORE_STALE: '0.05',
  DAYS_BEFORE_CLOSE: '0.06',
  DAYS_BEFORE_ANCIENT: '1',
  STALE_ISSUE_LABEL: 'closing-soon',
  EXEMPT_ISSUE_LABELS: 'go-away-bot',
  STALE_PR_LABEL: 'stale-pr',
  EXEMPT_PR_LABELS: 'go-away-bot',
  RESPONSE_REQUESTED_LABEL: 'response-requested',
  CFS_LABEL: 'closed-for-staleness',
  MINIMUM_UPVOTES_TO_EXEMPT: '1',
  ISSUE_TYPES: 'issues,pull_requests',
};

export const now = new Date(Date.now()).toISOString();

/**
 * Issue 256: Labelled with go-away-bot, no comments
 */
export const issue256 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/256',
  id: 172115562,
  node_id: 'MDU6SXNzdWUxNzIxMTU1NjI=',
  number: 256,
  title: 'Exempt',
  labels: [
    {
      id: 600797884,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/go-away-bot',
      name: 'go-away-bot',
    },
    {
      id: 600797885,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
      name: 'response-requested',
    }
  ],
  state: 'open',
  comments: 0,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: '2017-05-08T21:20:09Z',
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};
export const issue256Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: '2016-08-19T11:57:18Z',
    label: { name: 'go-away-bot', color: 'c5def5' },
  },
];

/**
 * Issue 257: Response-requested and closing-soon, then commented after the closing-soon label was added
 */
export const issue257 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/257',
  id: 172115557,
  node_id: 'MDU6SXNzdWUx7zIxMTU1NjI=',
  number: 257,
  title: 'Stale but commented',
  labels: [
    {
      id: 600797884,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
      name: 'response-requested',
    },
    {
      id: 600797885,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/closing-soon',
      name: 'closing-soon',
    },
  ],
  state: 'open',
  comments: 1,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: now,
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};
export const issue257Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: '2016-08-19T11:57:18Z',
    label: { name: 'closing-soon', color: 'c5def5' },
  },
  {
    id: 1073560792,
    node_id: 'MDEyOpxhYmVsZWRFdpVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560792',
    actor: {
      login: 'octocat',
      id: 583231,
      node_id: 'MDQ6VXNlcjU4MzIzMQ==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/583231?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: !1,
    },
    event: 'commented',
    commit_id: null,
    commit_url: null,
    created_at: now,
  },
];

/**
 * Issue 262: A response-requested issue that got a comment before the closing-soon label was added
 */
export const issue262 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/262',
  id: 179915562,
  node_id: 'MDU62XNzd6Ux7zIxMTU1NjI=',
  number: 262,
  title: 'Comments happened',
  labels: [
    {
      id: 600797884,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
      name: 'response-requested',
    },
  ],
  state: 'open',
  comments: 1,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: now,
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};
export const issue262Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: '2016-08-19T11:57:18Z',
    label: { name: 'response-requested', color: 'c5def5' },
  },
  {
    id: 1073560792,
    node_id: 'MDEyOpxhYmVsZWRFdpVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560792',
    actor: {
      login: 'octocat',
      id: 583231,
      node_id: 'MDQ6VXNlcjU4MzIzMQ==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/583231?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: !1,
    },
    event: 'commented',
    commit_id: null,
    commit_url: null,
    created_at: now,
  },
];

/**
 * Issue 261: A response-requested issue that is ready for the closing-soon label
 */
export const issue261 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/261',
  id: 172115561,
  node_id: 'MDU6SXNzd6Ux7zIxMTU1NjI=',
  number: 261,
  title: 'Mark me stale',
  labels: [
    {
      id: 600797884,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
      name: 'response-requested',
    },
  ],
  state: 'open',
  comments: 1,
  created_at: new Date(Date.parse(now) - 864e5 * Number.parseFloat(actionInputs.DAYS_BEFORE_STALE)).toISOString(),
  updated_at: new Date(Date.parse(now) - 864e5 * Number.parseFloat(actionInputs.DAYS_BEFORE_STALE)).toISOString(),
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};
export const issue261Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: new Date(Date.parse(now) - 864e5 * Number.parseFloat(actionInputs.DAYS_BEFORE_STALE)).toISOString(),
    label: { name: 'response-requested', color: 'c5def5' },
  },
];

/**
 * Issue 263: A response-requested issue that should not be touched. The stale timer has not expired
 */
export const issue263 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/263',
  id: 179916362,
  node_id: 'MDU62X63d6Ux7zIxMTU1NjI=',
  number: 263,
  title: 'Keep me open',
  labels: [
    {
      id: 600797884,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
      name: 'response-requested',
    },
  ],
  state: 'open',
  comments: 0,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: now,
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};
export const issue263Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: now,
    label: { name: 'response-requested', color: 'c5def5' },
  },
];

/**
 * Issue 258: An issue that has closing-soon and is ready for final closure
 */
export const issue258 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/258',
  id: 172115587,
  node_id: 'MD86SXNzdWUx7zIxMTU1NjI=',
  number: 258,
  title: 'Stale and close',
  labels: [
    {
      id: 600797885,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/closing-soon',
      name: 'closing-soon',
    },
  ],
  state: 'open',
  comments: 0,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: '2016-08-19T12:48:44Z',
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};
export const issue258Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: '2016-08-19T12:48:44Z',
    label: { name: 'closing-soon', color: 'c5def5' },
  },
];

/**
 * Issue 259: A closing-soon issue that should remain open. The timer has not expired
 */
export const issue259 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/259',
  id: 172115559,
  node_id: 'MD86SXNzdWUx759xMTU1NjI=',
  number: 259,
  title: 'Stale no close',
  labels: [
    {
      id: 600797885,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/closing-soon',
      name: 'closing-soon',
    },
  ],
  state: 'open',
  comments: 0,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: now,
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};
export const issue259Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: now,
    label: { name: 'closing-soon', color: 'c5def5' },
  },
];

/**
 * Issue 299: An issue that is ancient and should be closed
 */
export const issue299 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/299',
  id: 172115599,
  node_id: 'MDU6SXNzdWUxNzIx9TU1NjI=',
  number: 299,
  title: 'Ancient',
  state: 'open',
  comments: 0,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: '2016-08-19T11:57:17Z',
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};