import type { Endpoints } from '@octokit/types';

type issueType = Endpoints['GET /repos/{owner}/{repo}/issues']['response']['data'][0];
export const issue = {
  id: 1,
  node_id: 'MDU6SXNzdWUx',
  url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347',
  repository_url: 'https://api.github.com/repos/octocat/Hello-World',
  labels_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/labels{/name}',
  comments_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/comments',
  events_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/events',
  html_url: 'https://github.com/octocat/Hello-World/issues/1347',
  number: 1347,
  state: 'open',
  title: 'Found a bug',
  body: "I'm having a problem with this.",
  user: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  labels: [
    {
      id: 208045946,
      node_id: 'MDU6TGFiZWwyMDgwNDU5NDY=',
      url: 'https://api.github.com/repos/octocat/Hello-World/labels/bug',
      name: 'bug',
      description: "Something isn't working",
      color: 'f29513',
      default: true,
    },
  ],
  assignee: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  assignees: [
    {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
  ],
  milestone: {
    url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1',
    html_url: 'https://github.com/octocat/Hello-World/milestones/v1.0',
    labels_url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1/labels',
    id: 1002604,
    node_id: 'MDk6TWlsZXN0b25lMTAwMjYwNA==',
    number: 1,
    state: 'open',
    title: 'v1.0',
    description: 'Tracking milestone for version 1.0',
    creator: {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
    open_issues: 4,
    closed_issues: 8,
    created_at: '2011-04-10T20:09:31Z',
    updated_at: '2014-03-03T18:58:10Z',
    closed_at: '2013-02-12T13:22:01Z',
    due_on: '2012-10-09T23:39:01Z',
  },
  locked: true,
  active_lock_reason: 'too heated',
  comments: 0,
  pull_request: {
    url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347',
    html_url: 'https://github.com/octocat/Hello-World/pull/1347',
    diff_url: 'https://github.com/octocat/Hello-World/pull/1347.diff',
    patch_url: 'https://github.com/octocat/Hello-World/pull/1347.patch',
  },
  closed_at: null,
  created_at: '2011-04-22T13:33:48Z',
  updated_at: '2011-04-22T13:33:48Z',
  closed_by: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  author_association: 'COLLABORATOR',
  state_reason: 'completed',
} satisfies issueType;
export const issueWithoutLabels = {
  id: 1,
  node_id: 'MDU6SXNzdWUx',
  url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347',
  repository_url: 'https://api.github.com/repos/octocat/Hello-World',
  labels_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/labels{/name}',
  comments_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/comments',
  events_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/events',
  html_url: 'https://github.com/octocat/Hello-World/issues/1347',
  number: 1347,
  state: 'open',
  title: 'Found a bug',
  body: "I'm having a problem with this.",
  user: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  assignee: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  assignees: [
    {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
  ],
  milestone: {
    url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1',
    html_url: 'https://github.com/octocat/Hello-World/milestones/v1.0',
    labels_url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1/labels',
    id: 1002604,
    node_id: 'MDk6TWlsZXN0b25lMTAwMjYwNA==',
    number: 1,
    state: 'open',
    title: 'v1.0',
    description: 'Tracking milestone for version 1.0',
    creator: {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
    open_issues: 4,
    closed_issues: 8,
    created_at: '2011-04-10T20:09:31Z',
    updated_at: '2014-03-03T18:58:10Z',
    closed_at: '2013-02-12T13:22:01Z',
    due_on: '2012-10-09T23:39:01Z',
  },
  locked: true,
  active_lock_reason: 'too heated',
  comments: 0,
  pull_request: {
    url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347',
    html_url: 'https://github.com/octocat/Hello-World/pull/1347',
    diff_url: 'https://github.com/octocat/Hello-World/pull/1347.diff',
    patch_url: 'https://github.com/octocat/Hello-World/pull/1347.patch',
  },
  closed_at: null,
  created_at: '2011-04-22T13:33:48Z',
  updated_at: '2011-04-22T13:33:48Z',
  closed_by: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  author_association: 'COLLABORATOR',
  state_reason: 'completed',
} satisfies Omit<issueType, 'labels'>;

export const actionInputs = {
  GITHUB_REPOSITORY: 'aws-actions/stale-issue-cleanup',
  LOGLEVEL: 'DEBUG',
  'INPUT_REPO-TOKEN': 'FAKE-REPO-TOKEN',
  'INPUT_ANCIENT-ISSUE-MESSAGE': 'Ancient issue message.',
  'INPUT_ANCIENT-PR-MESSAGE': 'Ancient Pr message.',
  'INPUT_STALE-ISSUE-MESSAGE': 'Stale issue message.',
  'INPUT_STALE-PR-MESSAGE': 'Stale pr message.',
  'INPUT_DAYS-BEFORE-STALE': '0.05',
  'INPUT_DAYS-BEFORE-CLOSE': '0.06',
  'INPUT_DAYS-BEFORE-ANCIENT': '1',
  'INPUT_STALE-ISSUE-LABEL': 'closing-soon',
  'INPUT_EXEMPT-ISSUE-LABELS': 'go-away-bot',
  'INPUT_STALE-PR-LABEL': 'stale-pr',
  'INPUT_EXEMPT-PR-LABELS': 'go-away-bot',
  'INPUT_RESPONSE-REQUESTED-LABEL': 'response-requested',
  'INPUT_CLOSED-FOR-STALENESS-LABEL': 'closed-for-staleness',
  'INPUT_MINIMUM-UPVOTES-TO-EXEMPT': '1',
  'INPUT_ISSUE-TYPES': 'issues,pull_requests',
};

export const now = new Date(Date.now()).toISOString();

/**
 * Issue 256: Labelled with go-away-bot, no comments
 */
export const issue256 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/256',
  id: 172115562,
  node_id: 'MDU6SXNzdWUxNzIxMTU1NjI=',
  number: 256,
  title: 'Exempt',
  labels: [
    {
      id: 600797884,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/go-away-bot',
      name: 'go-away-bot',
    },
    {
      id: 600797885,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
      name: 'response-requested',
    },
  ],
  state: 'open',
  comments: 0,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: '2017-05-08T21:20:09Z',
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};
export const issue256Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: '2016-08-19T11:57:18Z',
    label: { name: 'go-away-bot', color: 'c5def5' },
  },
];

/**
 * Issue 257: Response-requested and closing-soon, then commented after the closing-soon label was added
 */
export const issue257 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/257',
  id: 172115557,
  node_id: 'MDU6SXNzdWUx7zIxMTU1NjI=',
  number: 257,
  title: 'Stale but commented',
  labels: [
    {
      id: 600797884,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
      name: 'response-requested',
    },
    {
      id: 600797885,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/closing-soon',
      name: 'closing-soon',
    },
  ],
  state: 'open',
  comments: 1,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: now,
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};
export const issue257Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: '2016-08-19T11:57:18Z',
    label: { name: 'closing-soon', color: 'c5def5' },
  },
  {
    id: 1073560792,
    node_id: 'MDEyOpxhYmVsZWRFdpVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560792',
    actor: {
      login: 'octocat',
      id: 583231,
      node_id: 'MDQ6VXNlcjU4MzIzMQ==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/583231?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: !1,
    },
    event: 'commented',
    commit_id: null,
    commit_url: null,
    created_at: now,
  },
];

/**
 * Issue 262: A response-requested issue that got a comment before the closing-soon label was added
 */
export const issue262 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/262',
  id: 179915562,
  node_id: 'MDU62XNzd6Ux7zIxMTU1NjI=',
  number: 262,
  title: 'Comments happened',
  labels: [
    {
      id: 600797884,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
      name: 'response-requested',
    },
  ],
  state: 'open',
  comments: 1,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: now,
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};
export const issue262Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: '2016-08-19T11:57:18Z',
    label: { name: 'response-requested', color: 'c5def5' },
  },
  {
    id: 1073560792,
    node_id: 'MDEyOpxhYmVsZWRFdpVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560792',
    actor: {
      login: 'octocat',
      id: 583231,
      node_id: 'MDQ6VXNlcjU4MzIzMQ==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/583231?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: !1,
    },
    event: 'commented',
    commit_id: null,
    commit_url: null,
    created_at: now,
  },
];

/**
 * Issue 261: A response-requested issue that is ready for the closing-soon label
 */
export const issue261 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/261',
  id: 172115561,
  node_id: 'MDU6SXNzd6Ux7zIxMTU1NjI=',
  number: 261,
  title: 'Mark me stale',
  labels: [
    {
      id: 600797884,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
      name: 'response-requested',
    },
  ],
  state: 'open',
  comments: 1,
  created_at: new Date(Date.parse(now) - 864e5 * Number.parseFloat(actionInputs['INPUT_DAYS-BEFORE-STALE'])).toISOString(),
  updated_at: new Date(Date.parse(now) - 864e5 * Number.parseFloat(actionInputs['INPUT_DAYS-BEFORE-STALE'])).toISOString(),
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};
export const issue261Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: new Date(Date.parse(now) - 864e5 * Number.parseFloat(actionInputs['INPUT_DAYS-BEFORE-STALE'])).toISOString(),
    label: { name: 'response-requested', color: 'c5def5' },
  },
];

/**
 * Issue 263: A response-requested issue that should not be touched. The stale timer has not expired
 */
export const issue263 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/263',
  id: 179916362,
  node_id: 'MDU62X63d6Ux7zIxMTU1NjI=',
  number: 263,
  title: 'Keep me open',
  labels: [
    {
      id: 600797884,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
      name: 'response-requested',
    },
  ],
  state: 'open',
  comments: 0,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: now,
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};
export const issue263Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: now,
    label: { name: 'response-requested', color: 'c5def5' },
  },
];

/**
 * Issue 258: An issue that has closing-soon and is ready for final closure
 */
export const issue258 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/258',
  id: 172115587,
  node_id: 'MD86SXNzdWUx7zIxMTU1NjI=',
  number: 258,
  title: 'Stale and close',
  labels: [
    {
      id: 600797885,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/closing-soon',
      name: 'closing-soon',
    },
  ],
  state: 'open',
  comments: 0,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: '2016-08-19T12:48:44Z',
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};
export const issue258Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: '2016-08-19T12:48:44Z',
    label: { name: 'closing-soon', color: 'c5def5' },
  },
];

/**
 * Issue 259: A closing-soon issue that should remain open. The timer has not expired
 */
export const issue259 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/259',
  id: 172115559,
  node_id: 'MD86SXNzdWUx759xMTU1NjI=',
  number: 259,
  title: 'Stale no close',
  labels: [
    {
      id: 600797885,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/closing-soon',
      name: 'closing-soon',
    },
  ],
  state: 'open',
  comments: 0,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: now,
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};
export const issue259Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: now,
    label: { name: 'closing-soon', color: 'c5def5' },
  },
];

/**
 * Issue 299: An issue that is ancient and should be closed
 */
export const issue299 = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/299',
  id: 172115599,
  node_id: 'MDU6SXNzdWUxNzIx9TU1NjI=',
  number: 299,
  title: 'Ancient',
  state: 'open',
  comments: 0,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: '2016-08-19T11:57:17Z',
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};

export const issue242Reactions = [
  {
    id: 1,
    node_id: 'MDg6UmVhY3Rpb24x',
    user: {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
    content: 'heart',
    created_at: '2016-05-20T20:09:31Z',
  },
  {
    id: 2,
    node_id: 'MDg6UmVhY3Rpb35x',
    user: {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
    content: '+1',
    created_at: '2016-05-20T20:09:31Z',
  },
  {
    id: 3,
    node_id: 'MDg6UmVhY3Rpb42x',
    user: {
      login: 'lehmanmj',
      id: 2,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/lehmanmj',
      html_url: 'https://github.com/lehmanmj',
      followers_url: 'https://api.github.com/users/lehmanmj/followers',
      following_url: 'https://api.github.com/users/lehmanmj/following{/other_user}',
      gists_url: 'https://api.github.com/users/lehmanmj/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/lehmanmj/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/lehmanmj/subscriptions',
      organizations_url: 'https://api.github.com/users/lehmanmj/orgs',
      repos_url: 'https://api.github.com/users/lehmanmj/repos',
      events_url: 'https://api.github.com/users/lehmanmj/events{/privacy}',
      received_events_url: 'https://api.github.com/users/lehmanmj/received_events',
      type: 'User',
      site_admin: false,
    },
    content: 'hooray',
    created_at: '2016-05-20T20:09:32Z',
  },
];

export const issue242 = {
  id: 123451234,
  node_id: 'MDU6SXNzdWUx',
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/242/',
  repository_url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup',
  labels_url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/242/labels{/name}',
  comments_url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/242/comments',
  events_url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/242/events',
  html_url: 'https://github.com/aws-actions/stale-issue-cleanup/issues/242',
  number: 242,
  state: 'open',
  title: 'Found a bug',
  body: "I'm having a problem with this.",
  user: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  labels: [],
  assignee: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  assignees: [
    {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
  ],
  milestone: {
    url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1',
    html_url: 'https://github.com/octocat/Hello-World/milestones/v1.0',
    labels_url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1/labels',
    id: 1002604,
    node_id: 'MDk6TWlsZXN0b25lMTAwMjYwNA==',
    number: 1,
    state: 'open',
    title: 'v1.0',
    description: 'Tracking milestone for version 1.0',
    creator: {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
    open_issues: 4,
    closed_issues: 8,
    created_at: '2011-04-10T20:09:31Z',
    updated_at: '2014-03-03T18:58:10Z',
    closed_at: '2013-02-12T13:22:01Z',
    due_on: '2012-10-09T23:39:01Z',
  },
  reactions: {
    url: 'https://github.com/repos/aws-actions/stale-issue-cleanup/issues/242/reactions',
    total_count: 1,
    '+1': 0,
    '-1': 0,
    laugh: 0,
    confused: 0,
    heart: 1,
    hooray: 0,
    eyes: 0,
    rocket: 0,
  },
  locked: true,
  active_lock_reason: 'too heated',
  comments: 0,
  pull_request: {
    url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347',
    html_url: 'https://github.com/octocat/Hello-World/pull/1347',
    diff_url: 'https://github.com/octocat/Hello-World/pull/1347.diff',
    patch_url: 'https://github.com/octocat/Hello-World/pull/1347.patch',
  },
  closed_at: null,
  created_at: '2011-04-22T13:33:48Z',
  updated_at: '2011-04-22T13:33:48Z',
  repository: {
    id: 1296269,
    node_id: 'MDEwOlJlcG9zaXRvcnkxMjk2MjY5',
    name: 'Hello-World',
    full_name: 'octocat/Hello-World',
    owner: {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
    private: false,
    html_url: 'https://github.com/octocat/Hello-World',
    description: 'This your first repo!',
    fork: false,
    url: 'https://api.github.com/repos/octocat/Hello-World',
    archive_url: 'https://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}',
    assignees_url: 'https://api.github.com/repos/octocat/Hello-World/assignees{/user}',
    blobs_url: 'https://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}',
    branches_url: 'https://api.github.com/repos/octocat/Hello-World/branches{/branch}',
    collaborators_url: 'https://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}',
    comments_url: 'https://api.github.com/repos/octocat/Hello-World/comments{/number}',
    commits_url: 'https://api.github.com/repos/octocat/Hello-World/commits{/sha}',
    compare_url: 'https://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}',
    contents_url: 'https://api.github.com/repos/octocat/Hello-World/contents/{+path}',
    contributors_url: 'https://api.github.com/repos/octocat/Hello-World/contributors',
    deployments_url: 'https://api.github.com/repos/octocat/Hello-World/deployments',
    downloads_url: 'https://api.github.com/repos/octocat/Hello-World/downloads',
    events_url: 'https://api.github.com/repos/octocat/Hello-World/events',
    forks_url: 'https://api.github.com/repos/octocat/Hello-World/forks',
    git_commits_url: 'https://api.github.com/repos/octocat/Hello-World/git/commits{/sha}',
    git_refs_url: 'https://api.github.com/repos/octocat/Hello-World/git/refs{/sha}',
    git_tags_url: 'https://api.github.com/repos/octocat/Hello-World/git/tags{/sha}',
    git_url: 'git:github.com/octocat/Hello-World.git',
    issue_comment_url: 'https://api.github.com/repos/octocat/Hello-World/issues/comments{/number}',
    issue_events_url: 'https://api.github.com/repos/octocat/Hello-World/issues/events{/number}',
    issues_url: 'https://api.github.com/repos/octocat/Hello-World/issues{/number}',
    keys_url: 'https://api.github.com/repos/octocat/Hello-World/keys{/key_id}',
    labels_url: 'https://api.github.com/repos/octocat/Hello-World/labels{/name}',
    languages_url: 'https://api.github.com/repos/octocat/Hello-World/languages',
    merges_url: 'https://api.github.com/repos/octocat/Hello-World/merges',
    milestones_url: 'https://api.github.com/repos/octocat/Hello-World/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}',
    pulls_url: 'https://api.github.com/repos/octocat/Hello-World/pulls{/number}',
    releases_url: 'https://api.github.com/repos/octocat/Hello-World/releases{/id}',
    ssh_url: 'git@github.com:octocat/Hello-World.git',
    stargazers_url: 'https://api.github.com/repos/octocat/Hello-World/stargazers',
    statuses_url: 'https://api.github.com/repos/octocat/Hello-World/statuses/{sha}',
    subscribers_url: 'https://api.github.com/repos/octocat/Hello-World/subscribers',
    subscription_url: 'https://api.github.com/repos/octocat/Hello-World/subscription',
    tags_url: 'https://api.github.com/repos/octocat/Hello-World/tags',
    teams_url: 'https://api.github.com/repos/octocat/Hello-World/teams',
    trees_url: 'https://api.github.com/repos/octocat/Hello-World/git/trees{/sha}',
    clone_url: 'https://github.com/octocat/Hello-World.git',
    mirror_url: 'git:git.example.com/octocat/Hello-World',
    hooks_url: 'https://api.github.com/repos/octocat/Hello-World/hooks',
    svn_url: 'https://svn.github.com/octocat/Hello-World',
    homepage: 'https://github.com',
    language: null,
    forks_count: 9,
    stargazers_count: 80,
    watchers_count: 80,
    size: 108,
    default_branch: 'master',
    open_issues_count: 0,
    is_template: true,
    topics: ['octocat', 'atom', 'electron', 'api'],
    has_issues: true,
    has_projects: true,
    has_wiki: true,
    has_pages: false,
    has_downloads: true,
    archived: false,
    disabled: false,
    visibility: 'public',
    pushed_at: '2011-01-26T19:06:43Z',
    created_at: '2011-01-26T19:01:12Z',
    updated_at: '2011-01-26T19:14:43Z',
    permissions: {
      admin: false,
      push: false,
      pull: true,
    },
    allow_rebase_merge: true,
    template_repository: null,
    temp_clone_token: 'ABTLWHOULUVAXGTRYU7OC2876QJ2O',
    allow_squash_merge: true,
    allow_auto_merge: false,
    delete_branch_on_merge: true,
    allow_merge_commit: true,
    subscribers_count: 42,
    network_count: 0,
    license: {
      key: 'mit',
      name: 'MIT License',
      url: 'https://api.github.com/licenses/mit',
      spdx_id: 'MIT',
      node_id: 'MDc6TGljZW5zZW1pdA==',
      html_url: 'https://github.com/licenses/mit',
    },
    forks: 1,
    open_issues: 1,
    watchers: 1,
  },
  author_association: 'COLLABORATOR',
};

export const issue242Timeline = [
  {
    id: 1073561592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073561592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: '2011-04-22T13:33:49Z',
    label: {},
  },
];
