export const issue = {
  id: 1,
  node_id: 'MDU6SXNzdWUx',
  url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347',
  repository_url: 'https://api.github.com/repos/octocat/Hello-World',
  labels_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/labels{/name}',
  comments_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/comments',
  events_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/events',
  html_url: 'https://github.com/octocat/Hello-World/issues/1347',
  number: 1347,
  state: 'open',
  title: 'Found a bug',
  body: "I'm having a problem with this.",
  user: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  labels: [
    {
      id: 208045946,
      node_id: 'MDU6TGFiZWwyMDgwNDU5NDY=',
      url: 'https://api.github.com/repos/octocat/Hello-World/labels/bug',
      name: 'bug',
      description: "Something isn't working",
      color: 'f29513',
      default: true,
    },
  ],
  assignee: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  assignees: [
    {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
  ],
  milestone: {
    url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1',
    html_url: 'https://github.com/octocat/Hello-World/milestones/v1.0',
    labels_url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1/labels',
    id: 1002604,
    node_id: 'MDk6TWlsZXN0b25lMTAwMjYwNA==',
    number: 1,
    state: 'open',
    title: 'v1.0',
    description: 'Tracking milestone for version 1.0',
    creator: {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
    open_issues: 4,
    closed_issues: 8,
    created_at: '2011-04-10T20:09:31Z',
    updated_at: '2014-03-03T18:58:10Z',
    closed_at: '2013-02-12T13:22:01Z',
    due_on: '2012-10-09T23:39:01Z',
  },
  locked: true,
  active_lock_reason: 'too heated',
  comments: 0,
  pull_request: {
    url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347',
    html_url: 'https://github.com/octocat/Hello-World/pull/1347',
    diff_url: 'https://github.com/octocat/Hello-World/pull/1347.diff',
    patch_url: 'https://github.com/octocat/Hello-World/pull/1347.patch',
  },
  closed_at: null,
  created_at: '2011-04-22T13:33:48Z',
  updated_at: '2011-04-22T13:33:48Z',
  closed_by: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  author_association: 'COLLABORATOR',
  state_reason: 'completed',
};

export const issueWithoutLabels = {
  node_id: 'MDU6SXNzdWUx',
  url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347',
  repository_url: 'https://api.github.com/repos/octocat/Hello-World',
  labels_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/labels{/name}',
  comments_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/comments',
  events_url: 'https://api.github.com/repos/octocat/Hello-World/issues/1347/events',
  html_url: 'https://github.com/octocat/Hello-World/issues/1347',
  number: 1347,
  state: 'open',
  title: 'Found a bug',
  body: "I'm having a problem with this.",
  user: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  assignee: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  assignees: [
    {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
  ],
  milestone: {
    url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1',
    html_url: 'https://github.com/octocat/Hello-World/milestones/v1.0',
    labels_url: 'https://api.github.com/repos/octocat/Hello-World/milestones/1/labels',
    id: 1002604,
    node_id: 'MDk6TWlsZXN0b25lMTAwMjYwNA==',
    number: 1,
    state: 'open',
    title: 'v1.0',
    description: 'Tracking milestone for version 1.0',
    creator: {
      login: 'octocat',
      id: 1,
      node_id: 'MDQ6VXNlcjE=',
      avatar_url: 'https://github.com/images/error/octocat_happy.gif',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: false,
    },
    open_issues: 4,
    closed_issues: 8,
    created_at: '2011-04-10T20:09:31Z',
    updated_at: '2014-03-03T18:58:10Z',
    closed_at: '2013-02-12T13:22:01Z',
    due_on: '2012-10-09T23:39:01Z',
  },
  locked: true,
  active_lock_reason: 'too heated',
  comments: 0,
  pull_request: {
    url: 'https://api.github.com/repos/octocat/Hello-World/pulls/1347',
    html_url: 'https://github.com/octocat/Hello-World/pull/1347',
    diff_url: 'https://github.com/octocat/Hello-World/pull/1347.diff',
    patch_url: 'https://github.com/octocat/Hello-World/pull/1347.patch',
  },
  closed_at: null,
  created_at: '2011-04-22T13:33:48Z',
  updated_at: '2011-04-22T13:33:48Z',
  closed_by: {
    login: 'octocat',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://github.com/images/error/octocat_happy.gif',
    gravatar_id: '',
    url: 'https://api.github.com/users/octocat',
    html_url: 'https://github.com/octocat',
    followers_url: 'https://api.github.com/users/octocat/followers',
    following_url: 'https://api.github.com/users/octocat/following{/other_user}',
    gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
    organizations_url: 'https://api.github.com/users/octocat/orgs',
    repos_url: 'https://api.github.com/users/octocat/repos',
    events_url: 'https://api.github.com/users/octocat/events{/privacy}',
    received_events_url: 'https://api.github.com/users/octocat/received_events',
    type: 'User',
    site_admin: false,
  },
  author_association: 'COLLABORATOR',
  state_reason: 'completed',
};
const now = '2019-12-31T00:00:00.000Z';
export const responseRequestedReplies = [
  {
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/256',
    id: 172115562,
    node_id: 'MDU6SXNzdWUxNzIxMTU1NjI=',
    number: 256,
    title: 'Exempt',
    labels: [
      {
        id: 600797884,
        node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
        url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/go-away-bot',
        name: 'go-away-bot',
      },
    ],
    state: 'open',
    comments: 0,
    created_at: '2016-08-19T11:57:17Z',
    updated_at: '2017-05-08T21:20:09Z',
    closed_at: '2016-08-19T12:48:43Z',
    author_association: 'NONE',
    body: null,
  },
  {
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/257',
    id: 172115557,
    node_id: 'MDU6SXNzdWUx7zIxMTU1NjI=',
    number: 257,
    title: 'Stale but commented',
    labels: [
      {
        id: 600797884,
        node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
        url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
        name: 'response-requested',
      },
      {
        id: 600797885,
        node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
        url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/closing-soon',
        name: 'closing-soon',
      },
    ],
    state: 'open',
    comments: 1,
    created_at: '2016-08-19T11:57:17Z',
    updated_at: now,
    closed_at: '2016-08-19T12:48:43Z',
    author_association: 'NONE',
    body: null,
  },
  {
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/261',
    id: 172115561,
    node_id: 'MDU6SXNzd6Ux7zIxMTU1NjI=',
    number: 261,
    title: 'Mark me stale',
    labels: [
      {
        id: 600797884,
        node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
        url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
        name: 'response-requested',
      },
    ],
    state: 'open',
    comments: 1,
    // created_at: new Date(Date.parse(now) - 864e5 * process.env.DAYS_BEFORE_STALE).toISOString(),
    created_at: new Date(
      Date.parse(now) - 864e5 * Number.parseFloat(process.env.DAYS_BEFORE_STALE ?? '0'),
    ).toISOString(),
    updated_at: new Date(
      Date.parse(now) - 864e5 * Number.parseFloat(process.env.DAYS_BEFORE_STALE ?? '0'),
    ).toISOString(),
    closed_at: '2016-08-19T12:48:43Z',
    author_association: 'NONE',
    body: null,
  },
  {
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/262',
    id: 179915562,
    node_id: 'MDU62XNzd6Ux7zIxMTU1NjI=',
    number: 262,
    title: 'Comments happened',
    labels: [
      {
        id: 600797884,
        node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
        url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
        name: 'response-requested',
      },
    ],
    state: 'open',
    comments: 1,
    created_at: '2016-08-19T11:57:17Z',
    updated_at: now,
    closed_at: '2016-08-19T12:48:43Z',
    author_association: 'NONE',
    body: null,
  },
  {
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/263',
    id: 179916362,
    node_id: 'MDU62X63d6Ux7zIxMTU1NjI=',
    number: 263,
    title: 'Keep me open',
    labels: [
      {
        id: 600797884,
        node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
        url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
        name: 'response-requested',
      },
    ],
    state: 'open',
    comments: 0,
    created_at: '2016-08-19T11:57:17Z',
    updated_at: now,
    closed_at: '2016-08-19T12:48:43Z',
    author_association: 'NONE',
    body: null,
  },
];

export const staleIssueReplies = [
  {
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/257',
    id: 172115557,
    node_id: 'MDU6SXNzdWUx7zIxMTU1NjI=',
    number: 257,
    title: 'Stale but commented',
    labels: [
      {
        id: 600797884,
        node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
        url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/response-requested',
        name: 'response-requested',
      },
      {
        id: 600797885,
        node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
        url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/closing-soon',
        name: 'closing-soon',
      },
    ],
    state: 'open',
    comments: 1,
    created_at: '2016-08-19T11:57:17Z',
    updated_at: now,
    closed_at: '2016-08-19T12:48:43Z',
    author_association: 'NONE',
    body: null,
  },
  {
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/258',
    id: 172115587,
    node_id: 'MD86SXNzdWUx7zIxMTU1NjI=',
    number: 258,
    title: 'Stale and close',
    labels: [
      {
        id: 600797885,
        node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
        url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/closing-soon',
        name: 'closing-soon',
      },
    ],
    state: 'open',
    comments: 0,
    created_at: '2016-08-19T11:57:17Z',
    updated_at: '2016-08-19T12:48:44Z',
    closed_at: '2016-08-19T12:48:43Z',
    author_association: 'NONE',
    body: null,
  },
  {
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/259',
    id: 172115559,
    node_id: 'MD86SXNzdWUx759xMTU1NjI=',
    number: 259,
    title: 'Stale no close',
    labels: [
      {
        id: 600797885,
        node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
        url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/closing-soon',
        name: 'closing-soon',
      },
    ],
    state: 'open',
    comments: 0,
    created_at: '2016-08-19T11:57:17Z',
    updated_at: now,
    closed_at: '2016-08-19T12:48:43Z',
    author_association: 'NONE',
    body: null,
  },
];

export const ancientIssueReplies = [
  {
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/299',
    id: 172115599,
    node_id: 'MDU6SXNzdWUxNzIx9TU1NjI=',
    number: 299,
    title: 'Ancient',
    state: 'open',
    comments: 0,
    created_at: '2016-08-19T11:57:17Z',
    updated_at: '2017-05-08T21:20:09Z',
    closed_at: '2016-08-19T12:48:43Z',
    author_association: 'NONE',
    body: null,
  },
];

export const issue256Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: '2016-08-19T11:57:18Z',
    label: { name: 'go-away-bot', color: 'c5def5' },
  },
];

export const issue257Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: '2016-08-19T11:57:18Z',
    label: { name: 'closing-soon', color: 'c5def5' },
  },
  {
    id: 1073560792,
    node_id: 'MDEyOpxhYmVsZWRFdpVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560792',
    actor: {
      login: 'octocat',
      id: 583231,
      node_id: 'MDQ6VXNlcjU4MzIzMQ==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/583231?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: !1,
    },
    event: 'commented',
    commit_id: null,
    commit_url: null,
    created_at: now,
  },
];

export const issue258Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: '2016-08-19T12:48:44Z',
    label: { name: 'closing-soon', color: 'c5def5' },
  },
];

export const issue259Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: now,
    label: { name: 'closing-soon', color: 'c5def5' },
  },
];

export const issue261Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    // created_at: new Date(Date.parse(now) - 864e5 * process.env.DAYS_BEFORE_STALE).toISOString(),
    created_at: new Date(
      Date.parse(now) - 864e5 * Number.parseFloat(process.env.DAYS_BEFORE_STALE ?? '0'),
    ).toISOString(),
    label: { name: 'response-requested', color: 'c5def5' },
  },
];

export const issue262Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: '2016-08-19T11:57:18Z',
    label: { name: 'response-requested', color: 'c5def5' },
  },
  {
    id: 1073560792,
    node_id: 'MDEyOpxhYmVsZWRFdpVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560792',
    actor: {
      login: 'octocat',
      id: 583231,
      node_id: 'MDQ6VXNlcjU4MzIzMQ==',
      avatar_url: 'https://avatars3.githubusercontent.com/u/583231?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/octocat',
      html_url: 'https://github.com/octocat',
      followers_url: 'https://api.github.com/users/octocat/followers',
      following_url: 'https://api.github.com/users/octocat/following{/other_user}',
      gists_url: 'https://api.github.com/users/octocat/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/octocat/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/octocat/subscriptions',
      organizations_url: 'https://api.github.com/users/octocat/orgs',
      repos_url: 'https://api.github.com/users/octocat/repos',
      events_url: 'https://api.github.com/users/octocat/events{/privacy}',
      received_events_url: 'https://api.github.com/users/octocat/received_events',
      type: 'User',
      site_admin: !1,
    },
    event: 'commented',
    commit_id: null,
    commit_url: null,
    created_at: now,
  },
];

export const issue263Timeline = [
  {
    id: 1073560592,
    node_id: 'MDEyOpxhvmVsZWRFdmVudDEwNzM1NjA1OTE=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/1073560592',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: now,
    label: { name: 'response-requested', color: 'c5def5' },
  },
];

export const issue256Reply = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/256',
  id: 172115562,
  node_id: 'MDU6SXNzdWUxNzIxMTU1NjI=',
  number: 256,
  title: 'Exempt?',
  labels: [
    {
      id: 600797884,
      node_id: 'MDU6TGFiZWw2MDA3OTc4ODQ=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/go-away-bot',
      name: 'go-away-bot',
    },
  ],
  state: 'open',
  comments: 0,
  created_at: '2016-08-19T11:57:17Z',
  updated_at: '2017-05-08T21:20:09Z',
  closed_at: '2016-08-19T12:48:43Z',
  author_association: 'NONE',
  body: null,
};

export const issue121Reply = {
  url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/121',
  id: 677599418,
  node_id: 'MDU6SXNzdWU2Nzc1OTk0MTg=',
  number: 121,
  title: 'Exempt too?',
  labels: [
    {
      id: 743820433,
      node_id: 'MDU6TGFiZWw3NDM4MjA0Mw=',
      url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/labels/help-wanted',
      name: 'help-wanted',
    },
  ],
  state: 'open',
  comments: 0,
  created_at: '2018-08-12T11:03:19Z',
  updated_at: '2018-08-15T11:07:32Z',
  closed_at: null,
  author_association: 'NONE',
  body: null,
};

export const issue121Timeline = [
  {
    id: 3647155910,
    node_id: 'MDEyOkxhYmVsZWRFdmVudDM2NDcxNTU5MTA=',
    url: 'https://api.github.com/repos/aws-actions/stale-issue-cleanup/issues/events/3647155910',
    actor: { login: 'octocat', id: 583231, node_id: 'MDQ6VXNlcjU4MzIzMQ==', type: 'User', site_admin: !1 },
    event: 'labeled',
    commit_id: null,
    commit_url: null,
    created_at: '2016-08-19T11:57:18Z',
    label: { name: 'help-wanted', color: '008672' },
  },
];
