---
extends:
- eslint:recommended
- plugin:node/recommended
- prettier
plugins:
- node
- prettier
env:
  es2022: true
rules:
  prettier/prettier: error
  block-scoped-var: error
  eqeqeq: error
  no-var: error
  prefer-const: error
  eol-last: error
  prefer-arrow-callback: error
  no-trailing-spaces: error
  quotes:
  - warn
  - single
  - avoidEscape: true
  no-restricted-properties:
  - error
  - object: describe
    property: only
  - object: it
    property: only
overrides:
- files:
  - "**/**.ts"
  - "**/**.tsx"
  parser: "@typescript-eslint/parser"
  plugins:
    - "@typescript-eslint"
  extends:
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  rules:
    "@typescript-eslint/no-non-null-assertion": 'off'
#    "@typescript-eslint/no-use-before-define": 'off'
#    "@typescript-eslint/no-warning-comments": 'off'
#    "@typescript-eslint/no-empty-function": 'off'
#    "@typescript-eslint/no-var-requires": 'off'
#    "@typescript-eslint/explicit-function-return-type": 'off'
#    "@typescript-eslint/explicit-module-boundary-types": 'off'
#    "@typescript-eslint/ban-types": 'off'
#    "@typescript-eslint/camelcase": 'off'
    "@typescript-eslint/no-misused-promises": ["error", {"checksvoidReturn": false}]
    node/no-missing-import: 'off'
    node/no-empty-function: 'off'
    node/no-unsupported-features/es-syntax: 'off'
    node/no-missing-require: 'off'
    node/shebang: 'off'
    node/no-unpublished-import:
    - error
    - convertPath:
        src/**/*.ts:
        - "^src/(.+?)\\.ts$"
        - "lib/$1.js"
#    no-dupe-class-members: 'off'
#    require-atomic-updates: 'off'
  parserOptions:
    project: './tsconfig.json'
    ecmaVersion: 2018
    sourceType: module
- files:
  - "**/**.mjs"
  parser: "@babel/eslint-parser"
  parserOptions:
    requireConfigFile: false
  rules:
    node/shebang: off
  plugins:
    - node
    - prettier
