---
name: "'Stale Issue Cleanup' Action for GitHub Actions"
description: 'Close issues and pull requests with no recent activity'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using `{{ secrets.GITHUB_TOKEN }}`'
    default: ${{ github.token }}
  minimum-upvotes-to-exempt:
    description: 'The minimum number of "upvotes" that an issue needs to have before never closing it.'
    default: 0
  dry-run:
    description: 'Set to true to not perform repository changes'
    default: false
  issue-expiration-label-map:
    description: 'A multiline input mapping labels with actions and destination labels for issues, applied after an expiration time. See README.md'
    default: |-
      ''
  issue-update-remove-labels:
    description: 'A comma-seperated list of labels that should be removed on issue update. See README.md'
    default: ''
  pr-expiration-label-map:
    description: 'A multiline input mapping labels with actions and destination labels for PRs, applied after an expiration time. See README.md'
    default: |-
      ''
  pr-update-remove-labels:
    description: 'A comma-seperated list of labels that should be removed on PR update. See README.md'
    default: ''

runs:
  using: 'node16'
  main: 'dist/index.js'
