---
name: Release Please
on:
  push:
    branches:
      - origin/release-please-integration

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.SECRETS_AWS_PACKAGING_ROLE_TO_ASSUME }}
          role-duration-seconds: 900
          role-session-name: ${{ github.run_id }}
      - name: Get git credentials
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          parse-json-secrets: true
          secret-ids: |
            OSDS,arn:aws:secretsmanager:us-west-2:206735643321:secret:github-aws-sdk-osds-automation-gebs9n

      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          token: ${{ steps.git-secrets.outputs.OSDS_ACCESS_TOKEN }}
